name: Deploy School Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      
      - name: Create env file
        run: touch .env

      - name: Assign value to .env
        run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

      - name: Build Docker Image
        run: docker build -t yuttana76/next-ecommerce .

      - name: Publish Image to docker hub
        run: docker push yuttana76/next-ecommerce:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      # - name: Stop container
      #   run: docker stop next-ecommerce

      # - name: Delete images
      #   run: docker image prune -f

      - name: Pull image from docker hub
        run: docker pull yuttana76/next-ecommerce:latest 

      - name: Delete old container
        run: docker rm -f next-ecommerce

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name next-ecommerce yuttana76/next-ecommerce
